# Generated by Django 4.2.17 on 2026-03-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_type', models.CharField(choices=[('docx', 'DOCX'), ('doc', 'DOC'), ('pdf', 'PDF'), ('xlsx', 'XLSX'), ('xls', 'XLS')], max_length=10, verbose_name='Тип файла')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('parsing', 'Парсинг'), ('parsed', 'Обработан'), ('error', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('parsed_data', models.JSONField(blank=True, default=list, verbose_name='Распарсенные данные')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Загруженный документ',
                'verbose_name_plural': 'Загруженные документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
