# Generated by Django 4.2.17 on 2026-03-14 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoplan', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parseddocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Разобранный документ', 'verbose_name_plural': 'Документы автопланирования'},
        ),
        migrations.AlterField(
            model_name='parseddocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружено'),
        ),
        migrations.AlterField(
            model_name='parseddocument',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='parseddocument',
            name='file',
            field=models.FileField(upload_to='parsed_documents/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='parseddocument',
            name='file_type',
            field=models.CharField(choices=[('docx', 'Word DOCX'), ('doc', 'Word DOC'), ('pdf', 'PDF'), ('xlsx', 'Excel XLSX'), ('xls', 'Excel XLS')], max_length=10, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='parseddocument',
            name='parsed_data',
            field=models.JSONField(default=list, verbose_name='Разобранные данные'),
        ),
        migrations.AlterField(
            model_name='parseddocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Загружен'), ('parsing', 'Разбор'), ('parsed', 'Разобран'), ('error', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='parseddocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddIndex(
            model_name='parseddocument',
            index=models.Index(fields=['status'], name='autoplan_pa_status_81d8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='parseddocument',
            index=models.Index(fields=['file_type'], name='autoplan_pa_file_ty_616e31_idx'),
        ),
        migrations.AddIndex(
            model_name='parseddocument',
            index=models.Index(fields=['-created_at'], name='autoplan_pa_created_b67d25_idx'),
        ),
    ]
