services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: rubezh_db
      POSTGRES_USER: rubezh_user
      POSTGRES_PASSWORD: rubezh_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app_network

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=rubezh.settings
      - DATABASE_URL=postgres://rubezh_user:rubezh_pass@db:5432/rubezh_db
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
    networks:
      - app_network

  celery_worker:
    build: ./backend
    command: celery -A rubezh worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=rubezh.settings
      - DATABASE_URL=postgres://rubezh_user:rubezh_pass@db:5432/rubezh_db
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge