# Generated by Django 4.2.17 on 2026-03-14 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='clearance_level',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень допуска'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('private', 'Рядовой'), ('corporal', 'Ефрейтор'), ('sergeant', 'Сержант'), ('staff_sergeant', 'Старшина'), ('warrant_officer', 'Прапорщик'), ('lieutenant', 'Лейтенант'), ('sr_lieutenant', 'Старший лейтенант'), ('captain', 'Капитан'), ('major', 'Майор'), ('lt_colonel', 'Подполковник'), ('colonel', 'Полковник')], default='private', max_length=30, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('commander', 'Командир'), ('deputy_commander', 'Заместитель командира'), ('department_head', 'Начальник отдела'), ('group_head', 'Начальник группы'), ('subordinate', 'Подчиненный')], default='subordinate', max_length=30, verbose_name='Роль'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rank'], name='users_user_rank_52a053_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['org_unit'], name='users_user_org_uni_43a91a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['clearance_level'], name='users_user_clearan_e1d170_idx'),
        ),
    ]
