# Generated by Django 4.2.17 on 2026-03-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('unit_type', models.CharField(choices=[('military_unit', 'Воинская часть'), ('department', 'Отдел'), ('group', 'Группа')], default='group', max_length=20, verbose_name='Тип подразделения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StructureChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_unit_name', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('change_type', models.CharField(choices=[('created', 'Создание'), ('renamed', 'Переименование'), ('moved', 'Перемещение'), ('commander_changed', 'Смена командира'), ('deleted', 'Удаление'), ('personnel_moved', 'Перемещение личного состава'), ('type_changed', 'Изменение типа')], max_length=30, verbose_name='Тип изменения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_data', models.JSONField(blank=True, default=dict, verbose_name='Старые данные')),
                ('new_data', models.JSONField(blank=True, default=dict, verbose_name='Новые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Изменение структуры',
                'verbose_name_plural': 'История изменений структуры',
                'ordering': ['-created_at'],
            },
        ),
    ]
