# Generated by Django 4.2.17 on 2026-03-14 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurechange',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор изменения'),
        ),
        migrations.AddField(
            model_name='structurechange',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='structure.orgunit'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_units', to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='structure.orgunit', verbose_name='Родительское подразделение'),
        ),
    ]
