# Generated by Django 4.2.17 on 2026-03-14 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='unit_type',
            field=models.CharField(choices=[('military_unit', 'Воинская часть'), ('department', 'Отдел'), ('group', 'Группа')], default='group', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='change_type',
            field=models.CharField(choices=[('created', 'Создано'), ('renamed', 'Переименовано'), ('moved', 'Перемещено'), ('commander_changed', 'Смена командира'), ('deleted', 'Удалено'), ('personnel_moved', 'Перемещение личного состава'), ('type_changed', 'Изменение типа')], max_length=30, verbose_name='Тип изменения'),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_changes', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='new_data',
            field=models.JSONField(default=dict, verbose_name='Новые данные'),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='old_data',
            field=models.JSONField(default=dict, verbose_name='Старые данные'),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='structure.orgunit', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='org_unit_name',
            field=models.CharField(max_length=255, verbose_name='Название подразделения'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['parent'], name='structure_o_parent__ff2267_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['commander'], name='structure_o_command_b395a5_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['unit_type'], name='structure_o_unit_ty_50eace_idx'),
        ),
        migrations.AddIndex(
            model_name='structurechange',
            index=models.Index(fields=['org_unit', '-created_at'], name='structure_s_org_uni_33521a_idx'),
        ),
        migrations.AddIndex(
            model_name='structurechange',
            index=models.Index(fields=['change_type'], name='structure_s_change__b3fd6f_idx'),
        ),
    ]
