# Generated by Django 4.2.17 on 2026-03-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500, verbose_name='Действие')),
                ('category', models.CharField(choices=[('auth', 'Авторизация'), ('tasks', 'Задачи'), ('structure', 'Структура'), ('security', 'Безопасность'), ('documents', 'Документы')], default='auth', max_length=20, verbose_name='Категория')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
            },
        ),
    ]
