# Generated by Django 4.2.17 on 2026-03-14 14:00

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('auth', 'Авторизация'), ('tasks', 'Задачи'), ('structure', 'Оргструктура'), ('security', 'Безопасность'), ('documents', 'Документы')], default='auth', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='User Agent'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['category', '-created_at'], name='audit_audit_categor_529cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address'], name='audit_audit_ip_addr_685e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['details'], name='audit_audit_details_f486e2_gin'),
        ),
    ]
