# Generated by Django 4.2.17 on 2026-05-06 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('category', models.CharField(choices=[('instructions', 'Инструкции'), ('regulations', 'Регламенты'), ('templates', 'Шаблоны'), ('other', 'Разное')], default='other', max_length=50, verbose_name='Категория')),
                ('file', models.FileField(upload_to='knowledge_base/%Y/%m/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ базы знаний',
                'verbose_name_plural': 'Документы базы знаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
