# Generated by Django 4.2.17 on 2026-05-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='category',
            field=models.CharField(choices=[('plans', 'Планы'), ('instructions', 'Инструкции'), ('regulations', 'Регламенты'), ('templates', 'Шаблоны'), ('other', 'Разное')], default='other', max_length=50, verbose_name='Категория'),
        ),
    ]
