# Generated by Django 4.2.17 on 2026-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasksubmission_taskcomment_submissionattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_milestone',
            field=models.BooleanField(default=False, verbose_name='Мероприятие календаря'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['start_date'], name='tasks_task_start_d_eb2c37_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['end_date'], name='tasks_task_end_dat_116fa9_idx'),
        ),
    ]
