# Generated by Django 4.2.17 on 2026-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_taskattachment_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_archived'], name='tasks_task_is_arch_7f263a_idx'),
        ),
    ]
