# Generated by Django 4.2.17 on 2026-05-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_is_archived_task_tasks_task_is_arch_7f263a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Глобальная задача (видна всем)'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_global'], name='tasks_task_is_glob_acbab6_idx'),
        ),
    ]
